<?php

global $_LANGMAIL;
$_LANGMAIL = array();

$_LANGMAIL['Newsletter confirmation'] = 'Tilmelding af nyhedsbrev';
$_LANGMAIL['Email verification'] = 'Bekræftelse af nyhedsbrev';
$_LANGMAIL['Newsletter voucher'] = 'Rabatkode for nyhedsbrev';
$_LANGMAIL['Your wishlist\\\'s link'] = 'Link til din ønskeliste';
$_LANGMAIL['Message from %1$s %2$s'] = 'Besked fra %1$s %2$s';
$_LANGMAIL['Your cart and your discount'] = 'Din kurv og din rabat';
$_LANGMAIL['Thanks for your order'] = 'Tak for din ordre';
$_LANGMAIL['You are one of our best customers'] = 'Du er en af vores bedste kunder';
$_LANGMAIL['We miss you'] = 'Vi savner dig';
$_LANGMAIL['Product available'] = 'Vare på lager';
$_LANGMAIL['Stock coverage'] = 'Lagerbeholdning';
$_LANGMAIL['Product out of stock'] = 'Vare udsolgt';
$_LANGMAIL['Congratulations!'] = 'Tillykke!';
$_LANGMAIL['%1$s sent you a link to %2$s'] = '%1$s sendte dig et link til %2$s';
$_LANGMAIL['Welcome!'] = 'Velkommen!';
$_LANGMAIL['Process the payment of your order'] = 'Bearbejd betalingen af din ordre';
$_LANGMAIL['Your message has been correctly sent #ct%1$s #tc%2$s'] = 'Din besked er blevet korrekt afsendt #ct%1$s #tc%2$s';
$_LANGMAIL['Your message has been correctly sent'] = 'Din besked er blevet afsendt';
$_LANGMAIL['Message from contact form'] = 'Besked fra kontaktformular';
$_LANGMAIL['New credit slip regarding your order'] = 'Ny kreditnota vedrørende din ordre';
$_LANGMAIL['Virtual product to download'] = 'Virtuel vare kan downloades';
$_LANGMAIL['Fwd: Customer message'] = 'Vs: Kundebesked';
$_LANGMAIL['Your guest account has been transformed to customer account'] = 'Din gæstekonto er blevet konverteret til en kundekonto';
$_LANGMAIL['Package in transit'] = 'Forsendelse undervejs';
$_LANGMAIL['Log: You have a new alert from your shop'] = 'Log: Du har en ny logbesked fra din webshop';
$_LANGMAIL['Your order has been changed'] = 'Din ordre er blevet ændret';
$_LANGMAIL['Order confirmation'] = 'Ordrebekræftelse';
$_LANGMAIL['Message from a customer'] = 'Besked fra en kunde';
$_LANGMAIL['New message regarding your order'] = 'Ny besked vedrørende din ordre';
$_LANGMAIL['Your order return state has changed'] = 'Status på din reklamation er ændret';
$_LANGMAIL['Your new password'] = 'Din nye adgangskode';
$_LANGMAIL['Password query confirmation'] = 'Glemt adgangskode';
$_LANGMAIL['An answer to your message is available #ct%1$s #tc%2$s'] = 'Der er kommet et svar på din besked #ct%1$s #tc%2$s';
$_LANGMAIL['New voucher regarding your order %s'] = 'Ny rabatkode vedrørende din ordre %s';
$_LANGMAIL['New order - #%06d'] = 'Ny ordre - #%06d';
